apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: run-after-etl
  namespace: workflow
spec:
  entrypoint: test-etl
  ttlStrategy:
    secondsAfterCompletion: 10 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 30     # Time to live after workflow is successful
    secondsAfterFailure: 30 
  templates:
      - name: test-etl
        dag:
          tasks:
            - name: test-run-after-etl
              template: test-run-after-etl-template

      - name: test-run-after-etl-template
        container:
          image: alpine:latest
          command: [sh, -c]
          args: [
            'echo "[1,2,3,4]"'
          ]
