apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: etl-webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: check-success
      eventSourceName: webhook
      eventName: example
      filters:
        data:
          - path: 'body.success'
            type: bool
            value:
              - 'true'
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: check-finished-etl-
              spec:
                ttlStrategy:
                  secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
                  secondsAfterSuccess: 3600     # Time to live after workflow is successful
                  secondsAfterFailure: 3600 
                workflowTemplateRef:
                  name: run-after-etl
