apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/victormacedo996/poc-argo
        revision: HEAD
        files:
          - path: "workflows/**/**/**/*"
  template:
    metadata:
      name: "workflow.{{path.basenameNormalized}}.{{path[3]}}.{{path[2]}}.{{path[1]}}"
      labels:
        workflow: "{{path.basenameNormalized}}"
        team: "{{path[3]}}"
        bu: "{{path[2]}}"
        environment: "{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/victormacedo996/poc-argo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: workflow
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResources=true
      info:
        - name: workflow
          value: "{{path.basenameNormalized}}"
        - name: team
          value: "{{path[3]}}"
        - name: bu
          value: "{{path[2]}}"
        - name: environment
          value: "{{path[1]}}"