apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: send-events
spec:
  schedule: "* * * * *"
  timezone: "America/Sao_Paulo"
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    entrypoint: etl-transform
    templates:
      - name: etl-transform
        dag:
          tasks:
            - name: etl-transform
              template: flip-coin-template

            - name: notify-success
              templateRef:
                name: notify-wf-template
                template: notify-template
              arguments:
                parameters:
                  - name: msg
                    value: '{"table_transform_name": "{{cronworkflow.name}}", "success": true}'
              depends: etl-transform.Succeeded

            - name: notify-failure
              templateRef:
                name: notify-wf-template
                template: notify-template
              arguments:
                parameters:
                  - name: msg
                    value: '{"table_transform_name": "{{cronworkflow.name}}", "success": false}'
              depends: etl-transform.Failed

      - name: flip-coin-template
        script:
          image: python:alpine3.6
          command: [python]
          source: |
            import random
            import sys
            results = random.randint(0,1)
            sys.exit(results)