apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: special-trigger
              spec:
                entrypoint: hello-world
                templates:
                  - name: hello-world
                    container:
                      image: alpine:latest
                      command: [sh, -c]
                      args: [
                        'echo hello-world'
                      ]
                  - name: hello-world-2
                    container:
                      image: alpine:latest
                      command: [sh, -c]
                      args: [
                        'echo hello-world-2'
                      ]
