# Create a dedicated ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-workflow-sa
  namespace: default

---
# Create a ClusterRole with full permissions for SparkApplications
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-role
rules:
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - sparkapplications/status
  - sparkapplications/finalizers
  verbs:
  - '*'

---
# Create a ClusterRoleBinding (not just a RoleBinding)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-operator-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---
# If you're using a custom ServiceAccount in your workflow, use this binding instead
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-workflow-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-operator-role
subjects:
- kind: ServiceAccount
  name: spark-workflow-sa
  namespace: default